// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ8wJWERM00aXKF94W-879UU77Qn9sJwY',
    appId: '1:400483238383:android:be4b67361de1abb4e4361a',
    messagingSenderId: '400483238383',
    projectId: 'nem-pho-f7f90',
    databaseURL: 'https://nem-pho-f7f90-default-rtdb.firebaseio.com',
    storageBucket: 'nem-pho-f7f90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMVY37c8OIfaZgz9HaoKGZuk_mGxQVTxM',
    appId: '1:400483238383:ios:3a043e51f244ad15e4361a',
    messagingSenderId: '400483238383',
    projectId: 'nem-pho-f7f90',
    databaseURL: 'https://nem-pho-f7f90-default-rtdb.firebaseio.com',
    storageBucket: 'nem-pho-f7f90.appspot.com',
    iosClientId: '400483238383-26598p0i0jvuudj27iqcdflddbv4vlra.apps.googleusercontent.com',
    iosBundleId: 'com.example.nemPho',
  );
}
